export const TYPE_SIZE = {
    /** 用于表示字符串数据，通常以 null 终止（NUL 0x00）表示字符串的结束。例：相机型号（Model）。 */
    Ascii: 'Variable',
    /** 注释文本，貌似与ASCII同类。例：UserComment */
    Comment: 'Variable',
    /** 原始的二进制数据（不规定格式）。例：图像软件（Software）。 */
    Undefined: 'Variable',
    /** 表示一个字节的单个整数（通常是 8 位）。例：图像的颜色空间（ColorSpace）。 */
    Byte: 1,
    /** 1 字节有符号整数 */
    SByte: 1,
    /**  16 位的无符号整数。例：图像方向（Orientation）。 */
    Short: 2,
    /** 16 位 有符号整数。例：光晕校正参数（VignettingCorrParams）。 */
    SShort: 2,
    /** 32 位的无符号整数。例：拍摄时间（DateTime）。 */
    Long: 4,
    /** 32 位有符号整数。例：曝光时间（ExposureTime）。 */
    SLong: 4,
    /** 一个分数，由两个 32 位的无符号整数构成，分别表示分子和分母。例：GPS 坐标（GPSLatitude）。 */
    Rational: 8,
    /** 带符号的分数，由两个 32 位有符号整数构成，表示分子和分母。例：相机的 ISO 设置（ISO） */
    SRational: 8,
    /** 32 位的单精度浮点数。例：相机的曝光补偿（ExposureBias） */
    Float: 4,
    SFloat: 4,
    /** 64 位的双精度浮点数。例：GPS 高度信息（GPSAltitude） */
    Double: 8,
    /** 8 字节双精度浮点数 */
    SDouble: 8,
    /** IFD（指向另一个 IFD 的指针） */
    IFD: 4,
    /** 8 字节无符号整数 */
    Long8: 8,
    /** 8 字节有符号整数 */
    SLong8: 8,
}

export type TExifDataType = keyof typeof TYPE_SIZE

export const TYPE_MAP: Record<string, TExifDataType> = {
    '0x0001': 'Byte',
    '0x0002': 'Ascii',
    '0x0003': 'Short',
    '0x0004': 'Long',
    '0x0005': 'Rational',
    '0x0006': 'SByte',
    '0x0007': 'Undefined',
    '0x0008': 'SShort',
    '0x0009': 'SLong',
    '0x000a': 'SRational',
    '0x000b': 'Float',
    '0x000c': 'Double',
    '0x000d': 'IFD',
    '0x000e': 'Long8',
    '0x000f': 'SLong8',
    '0x0010': 'SDouble',
}

/**
 * https://exiv2.org/tags.html
 */
export const IMAGE_TAGS: Record<string, { type: TExifDataType; key: string; }> = {
    '0x000b': { type: 'Ascii', key: 'ProcessingSoftware' },
    '0x00fe': { type: 'Long', key: 'NewSubfileType' },
    '0x00ff': { type: 'Short', key: 'SubfileType' },
    '0x0100': { type: 'Long', key: 'ImageWidth' },
    '0x0101': { type: 'Long', key: 'ImageLength' },
    '0x0102': { type: 'Short', key: 'BitsPerSample' },
    '0x0103': { type: 'Short', key: 'Compression' },
    '0x0106': { type: 'Short', key: 'PhotometricInterpretation' },
    '0x0107': { type: 'Short', key: 'Thresholding' },
    '0x0108': { type: 'Short', key: 'CellWidth' },
    '0x0109': { type: 'Short', key: 'CellLength' },
    '0x010a': { type: 'Short', key: 'FillOrder' },
    '0x010d': { type: 'Ascii', key: 'DocumentName' },
    '0x010e': { type: 'Ascii', key: 'ImageDescription' },
    '0x010f': { type: 'Ascii', key: 'Make' },
    '0x0110': { type: 'Ascii', key: 'Model' },
    '0x0111': { type: 'Long', key: 'StripOffsets' },
    '0x0112': { type: 'Short', key: 'Orientation' },
    '0x0115': { type: 'Short', key: 'SamplesPerPixel' },
    '0x0116': { type: 'Long', key: 'RowsPerStrip' },
    '0x0117': { type: 'Long', key: 'StripByteCounts' },
    '0x011a': { type: 'Rational', key: 'XResolution' },
    '0x011b': { type: 'Rational', key: 'YResolution' },
    '0x011c': { type: 'Short', key: 'PlanarConfiguration' },
    '0x011d': { type: 'Ascii', key: 'PageName' },
    '0x011e': { type: 'Rational', key: 'XPosition' },
    '0x011f': { type: 'Rational', key: 'YPosition' },
    '0x0122': { type: 'Short', key: 'GrayResponseUnit' },
    '0x0123': { type: 'Short', key: 'GrayResponseCurve' },
    '0x0124': { type: 'Long', key: 'T4Options' },
    '0x0125': { type: 'Long', key: 'T6Options' },
    '0x0128': { type: 'Short', key: 'ResolutionUnit' },
    '0x0129': { type: 'Short', key: 'PageNumber' },
    '0x012d': { type: 'Short', key: 'TransferFunction' },
    '0x0131': { type: 'Ascii', key: 'Software' },
    '0x0132': { type: 'Ascii', key: 'DateTime' },
    '0x013b': { type: 'Ascii', key: 'Artist' },
    '0x013c': { type: 'Ascii', key: 'HostComputer' },
    '0x013d': { type: 'Short', key: 'Predictor' },
    '0x013e': { type: 'Rational', key: 'WhitePoint' },
    '0x013f': { type: 'Rational', key: 'PrimaryChromaticities' },
    '0x0140': { type: 'Short', key: 'ColorMap' },
    '0x0141': { type: 'Short', key: 'HalftoneHints' },
    '0x0142': { type: 'Long', key: 'TileWidth' },
    '0x0143': { type: 'Long', key: 'TileLength' },
    '0x0144': { type: 'Short', key: 'TileOffsets' },
    '0x0145': { type: 'Long', key: 'TileByteCounts' },
    '0x014a': { type: 'Long', key: 'SubIFDs' },
    '0x014c': { type: 'Short', key: 'InkSet' },
    '0x014d': { type: 'Ascii', key: 'InkNames' },
    '0x014e': { type: 'Short', key: 'NumberOfInks' },
    '0x0150': { type: 'Byte', key: 'DotRange' },
    '0x0151': { type: 'Ascii', key: 'TargetPrinter' },
    '0x0152': { type: 'Short', key: 'ExtraSamples' },
    '0x0153': { type: 'Short', key: 'SampleFormat' },
    '0x0154': { type: 'Short', key: 'SMinSampleValue' },
    '0x0155': { type: 'Short', key: 'SMaxSampleValue' },
    '0x0156': { type: 'Short', key: 'TransferRange' },
    '0x0157': { type: 'Byte', key: 'ClipPath' },
    '0x0158': { type: 'SShort', key: 'XClipPathUnits' },
    '0x0159': { type: 'SShort', key: 'YClipPathUnits' },
    '0x015a': { type: 'Short', key: 'Indexed' },
    '0x015b': { type: 'Undefined', key: 'JPEGTables' },
    '0x015f': { type: 'Short', key: 'OPIProxy' },
    '0x0200': { type: 'Long', key: 'JPEGProc' },
    '0x0201': { type: 'Long', key: 'JPEGInterchangeFormat' },
    '0x0202': { type: 'Long', key: 'JPEGInterchangeFormatLength' },
    '0x0203': { type: 'Short', key: 'JPEGRestartInterval' },
    '0x0205': { type: 'Short', key: 'JPEGLosslessPredictors' },
    '0x0206': { type: 'Short', key: 'JPEGPointTransforms' },
    '0x0207': { type: 'Long', key: 'JPEGQTables' },
    '0x0208': { type: 'Long', key: 'JPEGDCTables' },
    '0x0209': { type: 'Long', key: 'JPEGACTables' },
    '0x0211': { type: 'Rational', key: 'YCbCrCoefficients' },
    '0x0212': { type: 'Short', key: 'YCbCrSubSampling' },
    '0x0213': { type: 'Short', key: 'YCbCrPositioning' },
    '0x0214': { type: 'Rational', key: 'ReferenceBlackWhite' },
    '0x02bc': { type: 'Byte', key: 'XMLPacket' },
    '0x4746': { type: 'Short', key: 'Rating' },
    '0x4749': { type: 'Short', key: 'RatingPercent' },
    '0x7032': { type: 'SShort', key: 'VignettingCorrParams' },
    '0x7035': { type: 'SShort', key: 'ChromaticAberrationCorrParams' },
    '0x7037': { type: 'SShort', key: 'DistortionCorrParams' },
    '0x800d': { type: 'Ascii', key: 'ImageID' },
    '0x828d': { type: 'Short', key: 'CFARepeatPatternDim' },
    '0x828e': { type: 'Byte', key: 'CFAPattern' },
    '0x828f': { type: 'Rational', key: 'BatteryLevel' },
    '0x8298': { type: 'Ascii', key: 'Copyright' },
    '0x829a': { type: 'Rational', key: 'ExposureTime' },
    '0x829d': { type: 'Rational', key: 'FNumber' },
    '0x83bb': { type: 'Long', key: 'IPTCNAA' },
    '0x8649': { type: 'Byte', key: 'ImageResources' },
    '0x8769': { type: 'Long', key: 'ExifTag' },
    '0x8773': { type: 'Undefined', key: 'InterColorProfile' },
    '0x8822': { type: 'Short', key: 'ExposureProgram' },
    '0x8824': { type: 'Ascii', key: 'SpectralSensitivity' },
    '0x8825': { type: 'Long', key: 'GPSTag' },
    '0x8827': { type: 'Short', key: 'ISOSpeedRatings' },
    '0x8828': { type: 'Undefined', key: 'OECF' },
    '0x8829': { type: 'Short', key: 'Interlace' },
    '0x882a': { type: 'SShort', key: 'TimeZoneOffset' },
    '0x882b': { type: 'Short', key: 'SelfTimerMode' },
    '0x9003': { type: 'Ascii', key: 'DateTimeOriginal' },
    '0x9102': { type: 'Rational', key: 'CompressedBitsPerPixel' },
    '0x9201': { type: 'SRational', key: 'ShutterSpeedValue' },
    '0x9202': { type: 'Rational', key: 'ApertureValue' },
    '0x9203': { type: 'SRational', key: 'BrightnessValue' },
    '0x9204': { type: 'SRational', key: 'ExposureBiasValue' },
    '0x9205': { type: 'Rational', key: 'MaxApertureValue' },
    '0x9206': { type: 'SRational', key: 'SubjectDistance' },
    '0x9207': { type: 'Short', key: 'MeteringMode' },
    '0x9208': { type: 'Short', key: 'LightSource' },
    '0x9209': { type: 'Short', key: 'Flash' },
    '0x920a': { type: 'Rational', key: 'FocalLength' },
    '0x920b': { type: 'Rational', key: 'FlashEnergy' },
    '0x920c': { type: 'Undefined', key: 'SpatialFrequencyResponse' },
    '0x920d': { type: 'Undefined', key: 'Noise' },
    '0x920e': { type: 'Rational', key: 'FocalPlaneXResolution' },
    '0x920f': { type: 'Rational', key: 'FocalPlaneYResolution' },
    '0x9210': { type: 'Short', key: 'FocalPlaneResolutionUnit' },
    '0x9211': { type: 'Long', key: 'ImageNumber' },
    '0x9212': { type: 'Ascii', key: 'SecurityClassification' },
    '0x9213': { type: 'Ascii', key: 'ImageHistory' },
    '0x9214': { type: 'Short', key: 'SubjectLocation' },
    '0x9215': { type: 'Rational', key: 'ExposureIndex' },
    '0x9216': { type: 'Byte', key: 'TIFFEPStandardID' },
    '0x9217': { type: 'Short', key: 'SensingMethod' },
    '0x9c9b': { type: 'Byte', key: 'XPTitle' },
    '0x9c9c': { type: 'Byte', key: 'XPComment' },
    '0x9c9d': { type: 'Byte', key: 'XPAuthor' },
    '0x9c9e': { type: 'Byte', key: 'XPKeywords' },
    '0x9c9f': { type: 'Byte', key: 'XPSubject' },
    '0xc4a5': { type: 'Undefined', key: 'PrintImageMatching' },
    '0xc612': { type: 'Byte', key: 'DNGVersion' },
    '0xc613': { type: 'Byte', key: 'DNGBackwardVersion' },
    '0xc614': { type: 'Ascii', key: 'UniqueCameraModel' },
    '0xc615': { type: 'Byte', key: 'LocalizedCameraModel' },
    '0xc616': { type: 'Byte', key: 'CFAPlaneColor' },
    '0xc617': { type: 'Short', key: 'CFALayout' },
    '0xc618': { type: 'Short', key: 'LinearizationTable' },
    '0xc619': { type: 'Short', key: 'BlackLevelRepeatDim' },
    '0xc61a': { type: 'Rational', key: 'BlackLevel' },
    '0xc61b': { type: 'SRational', key: 'BlackLevelDeltaH' },
    '0xc61c': { type: 'SRational', key: 'BlackLevelDeltaV' },
    '0xc61d': { type: 'Long', key: 'WhiteLevel' },
    '0xc61e': { type: 'Rational', key: 'DefaultScale' },
    '0xc61f': { type: 'Long', key: 'DefaultCropOrigin' },
    '0xc620': { type: 'Long', key: 'DefaultCropSize' },
    '0xc621': { type: 'SRational', key: 'ColorMatrix1' },
    '0xc622': { type: 'SRational', key: 'ColorMatrix2' },
    '0xc623': { type: 'SRational', key: 'CameraCalibration1' },
    '0xc624': { type: 'SRational', key: 'CameraCalibration2' },
    '0xc625': { type: 'SRational', key: 'ReductionMatrix1' },
    '0xc626': { type: 'SRational', key: 'ReductionMatrix2' },
    '0xc627': { type: 'Rational', key: 'AnalogBalance' },
    '0xc628': { type: 'Short', key: 'AsShotNeutral' },
    '0xc629': { type: 'Rational', key: 'AsShotWhiteXY' },
    '0xc62a': { type: 'SRational', key: 'BaselineExposure' },
    '0xc62b': { type: 'Rational', key: 'BaselineNoise' },
    '0xc62c': { type: 'Rational', key: 'BaselineSharpness' },
    '0xc62d': { type: 'Long', key: 'BayerGreenSplit' },
    '0xc62e': { type: 'Rational', key: 'LinearResponseLimit' },
    '0xc62f': { type: 'Ascii', key: 'CameraSerialNumber' },
    '0xc630': { type: 'Rational', key: 'LensInfo' },
    '0xc631': { type: 'Rational', key: 'ChromaBlurRadius' },
    '0xc632': { type: 'Rational', key: 'AntiAliasStrength' },
    '0xc633': { type: 'SRational', key: 'ShadowScale' },
    '0xc634': { type: 'Byte', key: 'DNGPrivateData' },
    '0xc635': { type: 'Short', key: 'MakerNoteSafety' },
    '0xc65a': { type: 'Short', key: 'CalibrationIlluminant1' },
    '0xc65b': { type: 'Short', key: 'CalibrationIlluminant2' },
    '0xc65c': { type: 'Rational', key: 'BestQualityScale' },
    '0xc65d': { type: 'Byte', key: 'RawDataUniqueID' },
    '0xc68b': { type: 'Byte', key: 'OriginalRawFileName' },
    '0xc68c': { type: 'Undefined', key: 'OriginalRawFileData' },
    '0xc68d': { type: 'Long', key: 'ActiveArea' },
    '0xc68e': { type: 'Long', key: 'MaskedAreas' },
    '0xc68f': { type: 'Undefined', key: 'AsShotICCProfile' },
    '0xc690': { type: 'SRational', key: 'AsShotPreProfileMatrix' },
    '0xc691': { type: 'Undefined', key: 'CurrentICCProfile' },
    '0xc692': { type: 'SRational', key: 'CurrentPreProfileMatrix' },
    '0xc6bf': { type: 'Short', key: 'ColorimetricReference' },
    '0xc6f3': { type: 'Byte', key: 'CameraCalibrationSignature' },
    '0xc6f4': { type: 'Byte', key: 'ProfileCalibrationSignature' },
    '0xc6f5': { type: 'Long', key: 'ExtraCameraProfiles' },
    '0xc6f6': { type: 'Byte', key: 'AsShotProfileName' },
    '0xc6f7': { type: 'Rational', key: 'NoiseReductionApplied' },
    '0xc6f8': { type: 'Byte', key: 'ProfileName' },
    '0xc6f9': { type: 'Long', key: 'ProfileHueSatMapDims' },
    '0xc6fa': { type: 'Float', key: 'ProfileHueSatMapData1' },
    '0xc6fb': { type: 'Float', key: 'ProfileHueSatMapData2' },
    '0xc6fc': { type: 'Float', key: 'ProfileToneCurve' },
    '0xc6fd': { type: 'Long', key: 'ProfileEmbedPolicy' },
    '0xc6fe': { type: 'Byte', key: 'ProfileCopyright' },
    '0xc714': { type: 'SRational', key: 'ForwardMatrix1' },
    '0xc715': { type: 'SRational', key: 'ForwardMatrix2' },
    '0xc716': { type: 'Byte', key: 'PreviewApplicationName' },
    '0xc717': { type: 'Byte', key: 'PreviewApplicationVersion' },
    '0xc718': { type: 'Byte', key: 'PreviewSettingsName' },
    '0xc719': { type: 'Byte', key: 'PreviewSettingsDigest' },
    '0xc71a': { type: 'Long', key: 'PreviewColorSpace' },
    '0xc71b': { type: 'Ascii', key: 'PreviewDateTime' },
    '0xc71c': { type: 'Undefined', key: 'RawImageDigest' },
    '0xc71d': { type: 'Undefined', key: 'OriginalRawFileDigest' },
    '0xc71e': { type: 'Long', key: 'SubTileBlockSize' },
    '0xc71f': { type: 'Long', key: 'RowInterleaveFactor' },
    '0xc725': { type: 'Long', key: 'ProfileLookTableDims' },
    '0xc726': { type: 'Float', key: 'ProfileLookTableData' },
    '0xc740': { type: 'Undefined', key: 'OpcodeList1' },
    '0xc741': { type: 'Undefined', key: 'OpcodeList2' },
    '0xc74e': { type: 'Undefined', key: 'OpcodeList3' },
    '0xc761': { type: 'Double', key: 'NoiseProfile' },
    '0xc763': { type: 'Byte', key: 'TimeCodes' },
    '0xc764': { type: 'SRational', key: 'FrameRate' },
    '0xc772': { type: 'SRational', key: 'TStop' },
    '0xc789': { type: 'Ascii', key: 'ReelName' },
    '0xc7a1': { type: 'Ascii', key: 'CameraLabel' },
    '0xc791': { type: 'Long', key: 'OriginalDefaultFinalSize' },
    '0xc792': { type: 'Long', key: 'OriginalBestQualityFinalSize' },
    '0xc793': { type: 'Long', key: 'OriginalDefaultCropSize' },
    '0xc7a3': { type: 'Long', key: 'ProfileHueSatMapEncoding' },
    '0xc7a4': { type: 'Long', key: 'ProfileLookTableEncoding' },
    '0xc7a5': { type: 'SRational', key: 'BaselineExposureOffset' },
    '0xc7a6': { type: 'Long', key: 'DefaultBlackRender' },
    '0xc7a7': { type: 'Byte', key: 'NewRawImageDigest' },
    '0xc7a8': { type: 'Double', key: 'RawToPreviewGain' },
    '0xc7b5': { type: 'Rational', key: 'DefaultUserCrop' },
    '0xc7e9': { type: 'Short', key: 'DepthFormat' },
    '0xc7ea': { type: 'Rational', key: 'DepthNear' },
    '0xc7eb': { type: 'Rational', key: 'DepthFar' },
    '0xc7ec': { type: 'Short', key: 'DepthUnits' },
    '0xc7ed': { type: 'Short', key: 'DepthMeasureType' },
    '0xc7ee': { type: 'Ascii', key: 'EnhanceParams' },
    '0xcd2d': { type: 'Undefined', key: 'ProfileGainTableMap' },
    '0xcd2e': { type: 'Ascii', key: 'SemanticName' },
    '0xcd30': { type: 'Ascii', key: 'SemanticInstanceID' },
    '0xcd31': { type: 'Short', key: 'CalibrationIlluminant3' },
    '0xcd32': { type: 'SRational', key: 'CameraCalibration3' },
    '0xcd33': { type: 'SRational', key: 'ColorMatrix3' },
    '0xcd34': { type: 'SRational', key: 'ForwardMatrix3' },
    '0xcd35': { type: 'Undefined', key: 'IlluminantData1' },
    '0xcd36': { type: 'Undefined', key: 'IlluminantData2' },
    '0xcd37': { type: 'Undefined', key: 'IlluminantData3' },
    '0xcd38': { type: 'Long', key: 'MaskSubArea' },
    '0xcd39': { type: 'Float', key: 'ProfileHueSatMapData3' },
    '0xcd3a': { type: 'SRational', key: 'ReductionMatrix3' },
    '0xcd3f': { type: 'Undefined', key: 'RGBTables' },
    '0xcd40': { type: 'Undefined', key: 'ProfileGainTableMap2' },
    '0xcd43': { type: 'Long', key: 'ColumnInterleaveFactor' },
    '0xcd44': { type: 'Undefined', key: 'ImageSequenceInfo' },
    '0xcd46': { type: 'Undefined', key: 'ImageStats' },
    '0xcd47': { type: 'Undefined', key: 'ProfileDynamicRange' },
    '0xcd48': { type: 'Ascii', key: 'ProfileGroupName' },
    '0xcd49': { type: 'Float', key: 'JXLDistance' },
    '0xcd4a': { type: 'Long', key: 'JXLEffort' },
    '0xcd4b': { type: 'Long', key: 'JXLDecodeSpeed' },
}

export const PHOTO_TAGS: Record<string, { type: TExifDataType; key: string; }> = {
    '0x829a': { key: 'ExposureTime', type: 'Rational' },
    '0x829d': { key: 'FNumber', type: 'Rational' },
    '0x8822': { key: 'ExposureProgram', type: 'Short' },
    '0x8824': { key: 'SpectralSensitivity', type: 'Ascii' },
    '0x8827': { key: 'ISOSpeedRatings', type: 'Short' },
    '0x8828': { key: 'OECF', type: 'Undefined' },
    '0x8830': { key: 'SensitivityType', type: 'Short' },
    '0x8831': { key: 'StandardOutputSensitivity', type: 'Long' },
    '0x8832': { key: 'RecommendedExposureIndex', type: 'Long' },
    '0x8833': { key: 'ISOSpeed', type: 'Long' },
    '0x8834': { key: 'ISOSpeedLatitudeyyy', type: 'Long' },
    '0x8835': { key: 'ISOSpeedLatitudezzz', type: 'Long' },
    '0x9000': { key: 'ExifVersion', type: 'Undefined' },
    '0x9003': { key: 'DateTimeOriginal', type: 'Ascii' },
    '0x9004': { key: 'DateTimeDigitized', type: 'Ascii' },
    '0x9010': { key: 'OffsetTime', type: 'Ascii' },
    '0x9011': { key: 'OffsetTimeOriginal', type: 'Ascii' },
    '0x9012': { key: 'OffsetTimeDigitized', type: 'Ascii' },
    '0x9101': { key: 'ComponentsConfiguration', type: 'Undefined' },
    '0x9102': { key: 'CompressedBitsPerPixel', type: 'Rational' },
    '0x9201': { key: 'ShutterSpeedValue', type: 'SRational' },
    '0x9202': { key: 'ApertureValue', type: 'Rational' },
    '0x9203': { key: 'BrightnessValue', type: 'SRational' },
    '0x9204': { key: 'ExposureBiasValue', type: 'SRational' },
    '0x9205': { key: 'MaxApertureValue', type: 'Rational' },
    '0x9206': { key: 'SubjectDistance', type: 'Rational' },
    '0x9207': { key: 'MeteringMode', type: 'Short' },
    '0x9208': { key: 'LightSource', type: 'Short' },
    '0x9209': { key: 'Flash', type: 'Short' },
    '0x920a': { key: 'FocalLength', type: 'Rational' },
    '0x9214': { key: 'SubjectArea', type: 'Short' },
    '0x927c': { key: 'MakerNote', type: 'Undefined' },
    '0x9286': { key: 'UserComment', type: 'Comment' },
    '0x9290': { key: 'SubSecTime', type: 'Ascii' },
    '0x9291': { key: 'SubSecTimeOriginal', type: 'Ascii' },
    '0x9292': { key: 'SubSecTimeDigitized', type: 'Ascii' },
    '0x9400': { key: 'Temperature', type: 'SRational' },
    '0x9401': { key: 'Humidity', type: 'Rational' },
    '0x9402': { key: 'Pressure', type: 'Rational' },
    '0x9403': { key: 'WaterDepth', type: 'SRational' },
    '0x9404': { key: 'Acceleration', type: 'Rational' },
    '0x9405': { key: 'CameraElevationAngle', type: 'SRational' },
    '0xa000': { key: 'FlashpixVersion', type: 'Undefined' },
    '0xa001': { key: 'ColorSpace', type: 'Short' },
    '0xa002': { key: 'PixelXDimension', type: 'Long' },
    '0xa003': { key: 'PixelYDimension', type: 'Long' },
    '0xa004': { key: 'RelatedSoundFile', type: 'Ascii' },
    '0xa005': { key: 'InteroperabilityTag', type: 'Long' },
    '0xa20b': { key: 'FlashEnergy', type: 'Rational' },
    '0xa20c': { key: 'SpatialFrequencyResponse', type: 'Undefined' },
    '0xa20e': { key: 'FocalPlaneXResolution', type: 'Rational' },
    '0xa20f': { key: 'FocalPlaneYResolution', type: 'Rational' },
    '0xa210': { key: 'FocalPlaneResolutionUnit', type: 'Short' },
    '0xa214': { key: 'SubjectLocation', type: 'Short' },
    '0xa215': { key: 'ExposureIndex', type: 'Rational' },
    '0xa217': { key: 'SensingMethod', type: 'Short' },
    '0xa300': { key: 'FileSource', type: 'Undefined' },
    '0xa301': { key: 'SceneType', type: 'Undefined' },
    '0xa302': { key: 'CFAPattern', type: 'Undefined' },
    '0xa401': { key: 'CustomRendered', type: 'Short' },
    '0xa402': { key: 'ExposureMode', type: 'Short' },
    '0xa403': { key: 'WhiteBalance', type: 'Short' },
    '0xa404': { key: 'DigitalZoomRatio', type: 'Rational' },
    '0xa405': { key: 'FocalLengthIn35mmFilm', type: 'Short' },
    '0xa406': { key: 'SceneCaptureType', type: 'Short' },
    '0xa407': { key: 'GainControl', type: 'Short' },
    '0xa408': { key: 'Contrast', type: 'Short' },
    '0xa409': { key: 'Saturation', type: 'Short' },
    '0xa40a': { key: 'Sharpness', type: 'Short' },
    '0xa40b': { key: 'DeviceSettingDescription', type: 'Undefined' },
    '0xa40c': { key: 'SubjectDistanceRange', type: 'Short' },
    '0xa420': { key: 'ImageUniqueID', type: 'Ascii' },
    '0xa430': { key: 'CameraOwnerName', type: 'Ascii' },
    '0xa431': { key: 'BodySerialNumber', type: 'Ascii' },
    '0xa432': { key: 'LensSpecification', type: 'Rational' },
    '0xa433': { key: 'LensMake', type: 'Ascii' },
    '0xa434': { key: 'LensModel', type: 'Ascii' },
    '0xa435': { key: 'LensSerialNumber', type: 'Ascii' },
    '0xa436': { key: 'ImageTitle', type: 'Ascii' },
    '0xa437': { key: 'Photographer', type: 'Ascii' },
    '0xa438': { key: 'ImageEditor', type: 'Ascii' },
    '0xa439': { key: 'CameraFirmware', type: 'Ascii' },
    '0xa43a': { key: 'RAWDevelopingSoftware', type: 'Ascii' },
    '0xa43b': { key: 'ImageEditingSoftware', type: 'Ascii' },
    '0xa43c': { key: 'MetadataEditingSoftware', type: 'Ascii' },
    '0xa460': { key: 'CompositeImage', type: 'Short' },
    '0xa461': { key: 'SourceImageNumberOfCompositeImage', type: 'Short' },
    '0xa462': { key: 'SourceExposureTimesOfCompositeImage', type: 'Undefined' },
    '0xa500': { key: 'Gamma', type: 'Rational' },

}

export const IOP_TAGS: Record<string, { type: TExifDataType; key: string; }> = {
    '0x0001': { key: 'InteroperabilityIndex', type: 'Ascii' },
    '0x0002': { key: 'InteroperabilityVersion', type: 'Undefined' },
    '0x1000': { key: 'RelatedImageFileFormat', type: 'Ascii' },
    '0x1001': { key: 'RelatedImageWidth', type: 'Long' },
    '0x1002': { key: 'RelatedImageLength', type: 'Long' },
}

export const GPSINFO_TAGS: Record<string, { type: TExifDataType; key: string; }> = {
    '0x0000': { key: 'GPSVersionID', type: 'Byte' },
    '0x0001': { key: 'GPSLatitudeRef', type: 'Ascii' },
    '0x0002': { key: 'GPSLatitude', type: 'Rational' },
    '0x0003': { key: 'GPSLongitudeRef', type: 'Ascii' },
    '0x0004': { key: 'GPSLongitude', type: 'Rational' },
    '0x0005': { key: 'GPSAltitudeRef', type: 'Byte' },
    '0x0006': { key: 'GPSAltitude', type: 'Rational' },
    '0x0007': { key: 'GPSTimeStamp', type: 'Rational' },
    '0x0008': { key: 'GPSSatellites', type: 'Ascii' },
    '0x0009': { key: 'GPSStatus', type: 'Ascii' },
    '0x000a': { key: 'GPSMeasureMode', type: 'Ascii' },
    '0x000b': { key: 'GPSDOP', type: 'Rational' },
    '0x000c': { key: 'GPSSpeedRef', type: 'Ascii' },
    '0x000d': { key: 'GPSSpeed', type: 'Rational' },
    '0x000e': { key: 'GPSTrackRef', type: 'Ascii' },
    '0x000f': { key: 'GPSTrack', type: 'Rational' },
    '0x0010': { key: 'GPSImgDirectionRef', type: 'Ascii' },
    '0x0011': { key: 'GPSImgDirection', type: 'Rational' },
    '0x0012': { key: 'GPSMapDatum', type: 'Ascii' },
    '0x0013': { key: 'GPSDestLatitudeRef', type: 'Ascii' },
    '0x0014': { key: 'GPSDestLatitude', type: 'Rational' },
    '0x0015': { key: 'GPSDestLongitudeRef', type: 'Ascii' },
    '0x0016': { key: 'GPSDestLongitude', type: 'Rational' },
    '0x0017': { key: 'GPSDestBearingRef', type: 'Ascii' },
    '0x0018': { key: 'GPSDestBearing', type: 'Rational' },
    '0x0019': { key: 'GPSDestDistanceRef', type: 'Ascii' },
    '0x001a': { key: 'GPSDestDistance', type: 'Rational' },
    '0x001b': { key: 'GPSProcessingMethod', type: 'Comment' },
    '0x001c': { key: 'GPSAreaInformation', type: 'Comment' },
    '0x001d': { key: 'GPSDateStamp', type: 'Ascii' },
    '0x001e': { key: 'GPSDifferential', type: 'Short' },
    '0x001f': { key: 'GPSHPositioningError', type: 'Rational' },
}

export const MPFINFO_TAGS: Record<string, { type: TExifDataType; key: string; }> = {
    '0xb000': { key: 'MPFVersion', type: 'Ascii' },
    '0xb001': { key: 'MPFNumberOfImages', type: 'Undefined' },
    '0xb002': { key: 'MPFImageList', type: 'Ascii' },
    '0xb003': { key: 'MPFImageUIDList', type: 'Long' },
    '0xb004': { key: 'MPFTotalFrames', type: 'Long' },
    '0xb101': { key: 'MPFIndividualNum', type: 'Long' },
    '0xb201': { key: 'MPFPanOrientation', type: 'Long' },
    '0xb202': { key: 'MPFPanOverlapH', type: 'Long' },
    '0xb203': { key: 'MPFPanOverlapV', type: 'Long' },
    '0xb204': { key: 'MPFBaseViewpointNum', type: 'Long' },
    '0xb205': { key: 'MPFConvergenceAngle', type: 'Long' },
    '0xb206': { key: 'MPFBaselineLength', type: 'Long' },
    '0xb207': { key: 'MPFVerticalDivergence', type: 'Long' },
    '0xb208': { key: 'MPFAxisDistanceX', type: 'Long' },
    '0xb209': { key: 'MPFAxisDistanceY', type: 'Long' },
    '0xb20a': { key: 'MPFAxisDistanceZ', type: 'Long' },
    '0xb20b': { key: 'MPFYawAngle', type: 'Long' },
    '0xb20c': { key: 'MPFPitchAngle', type: 'Long' },
    '0xb20d': { key: 'MPFRollAngle', type: 'Long' },
}